// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "gpio.h"

void LED_Butten(lv_event_t * e)
{
	// Your code here
	HAL_GPIO_TogglePin(GPIOE,GPIO_PIN_5);
}
